name = "AstroCoords"
uuid = "27fb9038-6a9d-4e07-8d5d-d0805b53c4cb"
authors = ["Jordan Murphy <jmurphy6895@gmail.com> and contributors"]
version = "0.2.4"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[extensions]
AstroCoordsZygoteExt = "Zygote"

[compat]
AllocCheck = "0.2"
Aqua = "0.8"
DifferentiationInterface = "0.6"
Diffractor = "0.2"
Enzyme = "0.13"
FiniteDiff = "2.26"
ForwardDiff = "0.10"
JET = "0.9"
LinearAlgebra = "1"
Mooncake = "0.4"
PolyesterForwardDiff = "0.1"
StaticArrays = "1.9"
Test = "1"
Zygote = "0.6"
julia = "1.10"

[extras]
AllocCheck = "9b6a8646-10ed-4001-bbdc-1d2f46dfbb1a"
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
Diffractor = "9f5e2b26-1114-432f-b630-d3fe2085c51c"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
PolyesterForwardDiff = "98d1487c-24ca-40b6-b7ab-df2af84e126b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["AllocCheck", "Aqua", "DifferentiationInterface", "Diffractor", "Enzyme", "FiniteDiff", "ForwardDiff", "JET", "Mooncake", "PolyesterForwardDiff", "Test", "Zygote"]
