name = "AstroCoords"
uuid = "27fb9038-6a9d-4e07-8d5d-d0805b53c4cb"
authors = ["Jordan Murphy <jmurphy6895@gmail.com> and contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Aqua = "0.8"
LinearAlgebra = "1"
StaticArrays = "1.9"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
